name: Generate-3D-Prints

on:

  #runs when there's a push to cad-staging
  push:
    branches:
      - 'cad-staging'
  
  #runs when there's a release
  release:
    types: [ published ]
  #runs manually
  workflow_dispatch:

jobs:
  export-mcad:

    name: Export MCAD
    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v2

    - name: Install FreeCAD Python library
      run:  |
        sudo apt -qq update
        sudo apt-get -qq -y install python3
        sudo apt-get -qq -y install python3-pip
        sudo apt-get -qq -y install qt5-default
        python3 -m pip install --upgrade pip
        pip install pyside2==5.12.6

    - name: Fetch FreeCAD
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "FreeCAD/FreeCAD"
        version: "tags/0.19.2"
        file: "FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage"
        target: "FreeCAD.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install FreeCad
      run:  |
        sudo chown runner:docker FreeCAD.AppImage
        pwd
        chmod +x FreeCAD.AppImage
        ./FreeCAD.AppImage --appimage-extract > /dev/null

    - name: Generate DXF files
      run: |
        cd .github/workflows/scripts
        python3 export-csm.py
      env:
        LD_LIBRARY_PATH: /home/runner/work/index/index/squashfs-root/usr/lib

    - name: Generate STL files
      run: |
        cd .github/workflows/scripts
        python3 export-3d-files.py

    - name: Compress STL and DXF files for Release
      run: |
        cd .github/workflows/scripts/stl-export
        zip -9 -j ~/LumenPnP-STLs-${{ github.event.release.tag_name }}.zip *.stl
        cd .github/workflows/scripts/csm-export
        zip -9 -j -u ~/LumenPnP-DXFs-${{ github.event.release.tag_name }}.zip *.dxf

    - name: Compress STL and DXF files for cad-staging
      run: |
        cd .github/workflows/scripts/stl-export
        zip -9 -j ~/LumenPnP-STLs-${{ github.sha }}.zip *.stl
        cd .github/workflows/scripts/csm-export
        zip -9 -j -u ~/LumenPnP-DXFs-${{ github.sha }}.zip *.dxf


    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: 3d-prints
        path: ~/3d-prints_${{ github.sha }}.zip
        if-no-files-found: error
        retention-days: 60

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          ~/3d-prints_${{ github.ref_name }}_${{ github.sha }}.zip
